---

- name: run the playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: set empty list for job ids
      set_fact: 
        job_id: []

    - name: Queue build of a project in 
      uri:
        url: https://ansible-ctrl.0e25.dynamic.opentlc.com/api/v2/jobs/
        user: admin
        password: redhat
        method: GET
        validate_certs: false
        force_basic_auth: yes
        status_code: 200
        return_content: true
      register: towerapi
      no_log: true

    - name: append
      set_fact:
        job_id : "{{ job_id + [item.id]  }}"
      loop: "{{towerapi.json.results}}"
      no_log: true

    - name: get the host information
      uri:
        url: https://ansible-ctrl.0e25.dynamic.opentlc.com/api/v2/jobs/{{item}}/job_host_summaries
        user: admin
        password: redhat
        method: GET
        validate_certs: false
        force_basic_auth: yes
        status_code: 200
        return_content: true
      loop: "{{job_id}}"
      register: vardata
      no_log: true


    - name: template
      template:
        src: template.j2
        dest: /tmp/tower
