---
- name: run the playbook
  hosts: localhost
  gather_facts: false
  vars: 
    start: "2022-04-14"
    end: "2022-04-18"
  vars_files:
    - vars.yml
  tasks:

    - name: set dates with time
      set_fact:
        start_date_time: "{{start}}T00:00:01"
        end_date_time: "{{end}}T23:59:59"


    - name: Queue build for getting count of jobs in ansible tower
      uri:
        url: https://phchbs-lx220059.eu.novartis.net/api/v2/jobs?started__gte={{start_date_time}}&finished__lte={{end_date_time}}
        user: "{{tower_user}}"
        password: "{{tower_pass}}"
        method: GET
        validate_certs: false
        force_basic_auth: yes
        status_code: 200
        return_content: true
      register: for_count
      no_log: true

    - name: calculate no of pages given page size is 200
      set_fact:
        page_no_before: "{{ for_count.json.count / 200 | round }}"

    - name: print page no before
      debug:
        var: page_no_before

    - name: set page no after
      set_fact: 
        no_of_pages: "{{page_no_before.split('.')[0] }}"

    - name: print page no after
      debug:
        var: no_of_pages

    - name: Query within Ansible tower for reporting
      uri:
        url: https://phchbs-lx220059.eu.novartis.net/api/v2/jobs?started__gte={{start_date_time}}&finished__lte={{end_date_time}}&page_size=200&page={{item}}
        user: "{{tower_user}}"
        password: "{{tower_pass}}"
        method: GET
        validate_certs: false
        force_basic_auth: yes
        status_code: 200
        return_content: true
      register: towerapi
      with_sequence: start=1 end={{no_of_pages}}
      no_log: true

    - name: template job_id
      template:
        src: job_id.j2
        dest: jobid.yml
    
    - name: include variable
      include_vars: jobid.yml

    - name: get the host information
      uri:
        url: https://phchbs-lx220059.eu.novartis.net/api/v2/jobs/{{item}}/job_host_summaries
        user: "{{tower_user}}"
        password: "{{tower_pass}}"
        method: GET
        validate_certs: false
        force_basic_auth: yes
        status_code: 200
        return_content: true
      loop: "{{job_id}}"
      register: vardata
      no_log: true
    
    - name: template
      template:
        src: template.j2
        dest: per-host-timeframe.csv

    - name: send email as attachment
      mail: 
        host: mail.novartis.com
        port: 25
        from: runbook.automation@novartis.com
        to: "{{mail_reciever}}"
        subject: Ansible Tower Job Report from {{start}} to {{end}}
        attach:
          - per-host-timeframe.csv
      no_log: true
